from MazeGraph import buildGraph
import heapq

"""This file implements A* Search on a grap of node objects. In order to use the function in another file simply import aStar, and call it with start and goal positions
as tuples (I messed around with just calling the object but I feel this is more intuitive and easier to use), as well as the list generated by buildGraph. Currently
The function returns a list of node objects in order of the shortest path between the points. Likely for graphical purposes we will need to call graphical updates in the while loop,
 but for now I just have it print the path once it's found. The heuristic used is the Manhattan distance, which is pretty standard."""

x= buildGraph("QuickFind",10,1,4,4, verbose=True,outputArray=True)  #should be 4 arrays of 4 elements
x=x["List"]

def aStar(start, goal, graph):
    """Runs A* Search On a graph of node objects"""
    startNode = graph[start[1]][start[0]]
    goalNode = graph[goal[1]][goal[0]]

    priority_queue = []
    counter = 0
    heapq.heappush(priority_queue, (0, counter, startNode))
    counter += 1
    came_from = {}

    
    gscore = {node: float('inf') for row in graph for node in row} #G Score is the cost from start to current node - initialize to inf since we haven't "discovered" them yet
    gscore[startNode] = 0   #initialize first to 0 since its the start node...
    f_score = {node: float('inf') for row in graph for node in row} # f score is gscore plus heuristic distance (core of A*)
    f_score[startNode] = heuristic(start, goal)


    #print("gscore:", gscore)
    #print("fscore:", f_score)

    while priority_queue: #this whole algorith is pretty much a priority queue based on f_score
        current = heapq.heappop(priority_queue)[2]
        if current == goalNode: #Success Condition
            path = []
            while current in came_from:
                path.append(current)
                current = came_from[current]
            path.append(startNode)
            path.reverse()
            print("Path found: from", startNode.index, "to", goalNode.index, ":", [(node.index) for node in path])
            return path
        
        for neighbor in get_neighbors(current, graph): #for each neighbor, calculate tentative gscore and update if it's better than the previously known gscore
            tentative_gscore = gscore[current] + 1
            if tentative_gscore < gscore[neighbor]:
                came_from[neighbor] = current
                gscore[neighbor] = tentative_gscore
                f_score[neighbor] = gscore[neighbor] + heuristic((neighbor.x, neighbor.y), goal)
                if neighbor not in [i[2] for i in priority_queue]:
                    heapq.heappush(priority_queue, (f_score[neighbor], counter, neighbor))
                    counter += 1
    return



def get_neighbors(node, graph):
    """Checks All Directions for Walls, if no wall, adds to neighbors list"""
    neighbors = []
    for direction in ['N', 'S', 'E', 'W']:
        if getattr(node, direction) == 0:  # If there's no wall
            if direction == 'N' and node.NIndex[1] >= 0:
                neighbors.append(graph[node.NIndex[1]][node.NIndex[0]])
            elif direction == 'S' and node.SIndex[1] < len(graph):
                neighbors.append(graph[node.SIndex[1]][node.SIndex[0]])
            elif direction == 'E' and node.EIndex[0] < len(graph[0]):
                neighbors.append(graph[node.EIndex[1]][node.EIndex[0]])
            elif direction == 'W' and node.WIndex[0] >= 0:
                neighbors.append(graph[node.WIndex[1]][node.WIndex[0]])
    return neighbors


def heuristic(a, b):
    """Manhattan distance heuristic for grid-based pathfinding."""
    return abs(a[0] - b[0]) + abs(a[1] - b[1])




#Run Astar with the start and goal positions on the generated graph
aStar((0,0),(3,3),x)



